import { prisma } from "../../core/lib/prisma";

export const PAKISTAN_CITIES = [
  // Capital & Punjab
  "Islamabad",
  "Lahore",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Gujranwala",
  "Gujrat",
  "Sialkot",
  "Bahawalpur",
  "Rahim Yar Khan",
  "Sargodha",
  "Sheikhupura",
  "Kasur",
  "Sahiwal",
  "Okara",
  "Jhang",
  "Khanewal",
  "Dera Ghazi Khan",
  "Muzaffargarh",
  "Vehari",
  "Mianwali",
  "Chakwal",
  "Attock",
  "Jhelum",
  "Taxila",
  "Wah Cantt",
  "Chiniot",
  "Toba Tek Singh",
  "Mandi Bahauddin",
  "Hafizabad",
  "Narowal",
  "Nankana Sahib",
  "Bhakkar",
  "Layyah",
  "Khushab",
  "Lodhran",
  "Bahawalnagar",
  "Pakpattan",
  "Rajanpur",
  "Kamoke",
  "Muridke",
  "Ferozewala",
  // Sindh
  "Karachi",
  "Hyderabad",
  "Sukkur",
  "Larkana",
  "Nawabshah",
  "Mirpur Khas",
  "Khairpur",
  "Jacobabad",
  "Shikarpur",
  "Dadu",
  "Badin",
  "Thatta",
  "Ghotki",
  "Sanghar",
  "Umerkot",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Matiari",
  "Qambar Shahdadkot",
  "Kashmore",
  "Naushahro Feroze",
  "Mithi",
  "Sujawal",
  "Jamshoro",
  // Khyber Pakhtunkhwa
  "Peshawar",
  "Mardan",
  "Abbottabad",
  "Mingora",
  "Kohat",
  "Bannu",
  "Dera Ismail Khan",
  "Charsadda",
  "Nowshera",
  "Swabi",
  "Haripur",
  "Mansehra",
  "Batkhela",
  "Buner",
  "Shangla",
  "Chitral",
  "Hangu",
  "Karak",
  "Lakki Marwat",
  "Tank",
  "Timergara",
  "Parachinar",
  "Landi Kotal",
  "Khar",
  "Ghalanai",
  "Miranshah",
  "Wana",
  // Balochistan
  "Quetta",
  "Khuzdar",
  "Turbat",
  "Chaman",
  "Sibi",
  "Zhob",
  "Loralai",
  "Gwadar",
  "Panjgur",
  "Mastung",
  "Kalat",
  "Uthal",
  "Ziarat",
  "Pishin",
  "Musakhel",
  "Barkhan",
  "Kohlu",
  "Dera Bugti",
  "Dera Allah Yar",
  "Dera Murad Jamali",
  // Gilgit-Baltistan
  "Gilgit",
  "Skardu",
  "Karimabad",
  "Gupis",
  "Astore",
  "Shigar",
  "Nagir",
  // Azad Kashmir
  "Muzaffarabad",
  "Mirpur",
  "Kotli",
  "Bhimber",
  "Rawalakot",
  "Bagh",
  "Haveli",
];

export async function seedCities() {
  const created = [];
  for (const name of PAKISTAN_CITIES) {
    const existing = await prisma.city.findUnique({ where: { name } });
    if (existing) continue;
    created.push(await prisma.city.create({ data: { name } }));
  }
  return created;
}
