export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "SALE.CREATE": "Sale created",
  "SALE_RETURN.CREATE": "Sale return created",
  "PURCHASE.CREATE": "Purchase created",
  "PURCHASE_RETURN.CREATE": "Purchase return created",
  "VOUCHER.CREATE": "Voucher created",
  "VOUCHER.UPDATE": "Voucher updated",
  "VOUCHER.REVERSE": "Voucher reversed",
  "EXPENSE.CREATE": "Expense added",
  "EXPENSE.UPDATE": "Expense updated",
  "EXPENSE.DELETE": "Expense deleted",
  "CREDIT.COLLECT": "Credit collected",
  "PRODUCT.CREATE": "Product added",
  "PRODUCT.UPDATE": "Product updated",
  "PRODUCT.DELETE": "Product deleted",
  "PRODUCT.IMPORT": "Products imported",
  "UNIT.CREATE": "Unit added",
  "UNIT.UPDATE": "Unit updated",
  "UNIT.DELETE": "Unit deleted",
  "UNIT.IMPORT": "Units imported",
  "UNIT.ADJUST": "Stock adjusted",
  "BRAND.CREATE": "Brand added",
  "BRAND.UPDATE": "Brand updated",
  "BRAND.DELETE": "Brand deleted",
  "BRAND.DEACTIVATE": "Brand deactivated",
  "CATEGORY.CREATE": "Category added",
  "CATEGORY.UPDATE": "Category updated",
  "CATEGORY.DELETE": "Category deleted",
  "CATEGORY.DEACTIVATE": "Category deactivated",
  "COLOR.CREATE": "Color added",
  "COLOR.UPDATE": "Color updated",
  "COLOR.DELETE": "Color deleted",
  "COLOR.DEACTIVATE": "Color deactivated",
  "CONTACT.CREATE": "Contact added",
  "CONTACT.UPDATE": "Contact updated",
  "CONTACT.DELETE": "Contact deleted",
  "CONTACT.IMPORT": "Contacts imported",
  "RESERVATION.CREATE": "Reservation created",
  "RESERVATION.CANCEL": "Reservation cancelled",
  "RESERVATION.RETURN": "Consignment returned",
  "RESERVATION.REFUND_PAID": "Refund processed",
  "BANK_ACCOUNT.CREATE": "Bank account added",
  "BANK_ACCOUNT.UPDATE": "Bank account updated",
  "BANK_ACCOUNT.DELETE": "Bank account deleted",
  "BANK_ACCOUNT.SET_DEFAULT": "Default bank set",
  "USER.CREATE": "User added",
  "USER.UPDATE": "User updated",
  "USER.DELETE": "User deleted",
  "USER.CHANGE_PIN": "PIN changed",
  "COMPANY.UPDATE": "Shop details updated",
  "PRINT.CREATE": "Print layout created",
  "PRINT.UPDATE": "Print layout updated",
  "PRINT.DELETE": "Print layout deleted",
  "PRINT.SET_DEFAULT": "Default print set",
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action.toLowerCase().replace(/_/g, " ");
}

export const AUDIT_TEXT = {
  title: "Activity Log",
  subtitle: "A record of every action taken across the shop.",
  searchPlaceholder: "Search by reference or details…",
  allActions: "All actions",
  allEntities: "All entities",
  allUsers: "All users",
  loading: "Loading activity…",
  noData: "No activity recorded yet.",
  noMatch: "No activity matches these filters.",
  entity: "Entity",
  action: "Action",
  details: "Details",
  entityRef: "Ref",
  time: "Time",
  rows: "entries",
} as const;
