export const AUTH = {
  unauthorizedEvent: "fig.auth.unauthorized",
  rememberedUsersKey: "fig.auth.rememberedUsers",
  rememberedTitle: "Recent users",
  rememberHint: "Select a user to fill in the username.",
  removeAll: "Clear",
  removedAll: "Cleared recent users",
  title: "Sign in to continue",
  username: "Username",
  usernamePlaceholder: "e.g. ARSLAN",
  enterPin: "Enter PIN",
  userRequired: "Enter your username.",
  userNotFound: "No user found with that username.",
  userInactive: "This account is inactive. Ask an admin to reactivate it.",
  invalidPin: "Invalid PIN. Try again.",
  rateLimited: "Too many attempts. Please wait and try again.",
  loginSuccess: "Welcome back",
} as const;
