export const AUTH = {
  unauthorizedEvent: "dost.auth.unauthorized",
  rememberedUsersKey: "dost.auth.rememberedUsers",
  rememberedTitle: "Recent users",
  rememberHint: "Select a user to fill in the username.",
  removeAll: "Clear",
  removedAll: "Cleared recent users",
  title: "Sign in to continue",
  username: "Username",
  usernamePlaceholder: "e.g. arslan",
  enterPin: "Enter PIN",
  userRequired: "Enter your username.",
  userNotFound: "No user found with that username.",
  invalidPin: "Invalid PIN. Try again.",
  loginSuccess: "Welcome back",
} as const;
