export const DASHBOARD_KPIS = [
  { label: "Today's Sales", value: "Rs 0" },
  { label: "Net Profit", value: "Rs 0" },
  { label: "Units Sold", value: "0" },
  { label: "Units In Stock", value: "0" },
] as const;

export const DASHBOARD_PLACEHOLDERS = [
  "Sales chart coming soon",
  "New vs Used breakdown coming soon",
] as const;

export const ACTIVITY_ACTION_LABELS: Record<string, string> = {
  "SALE.CREATE": "Sale created",
  "PURCHASE.CREATE": "Purchase made",
  "SALE_RETURN.CREATE": "Sale returned",
  "PURCHASE_RETURN.CREATE": "Purchase returned",
  "RESERVATION.CREATE": "Reservation added",
  "RESERVATION.CANCEL": "Reservation cancelled",
  "RESERVATION.RETURN": "Consignment returned",
  "RESERVATION.REFUND_PAID": "Refund paid",
  "VOUCHER.CREATE": "Voucher created",
  "VOUCHER.UPDATE": "Voucher updated",
  "VOUCHER.REVERSE": "Voucher reversed",
  "CREDIT.COLLECT": "Credit collected",
  "EXPENSE.CREATE": "Expense added",
  "EXPENSE.UPDATE": "Expense updated",
  "EXPENSE.DELETE": "Expense deleted",
  "CONTACT.CREATE": "Contact added",
  "CONTACT.UPDATE": "Contact updated",
  "CONTACT.DELETE": "Contact deleted",
  "CONTACT.IMPORT": "Contacts imported",
  "PRODUCT.CREATE": "Product added",
  "PRODUCT.UPDATE": "Product updated",
  "PRODUCT.DELETE": "Product deleted",
  "PRODUCT.IMPORT": "Products imported",
  "UNIT.CREATE": "Unit added",
  "UNIT.UPDATE": "Unit updated",
  "UNIT.DELETE": "Unit deleted",
  "UNIT.IMPORT": "Units imported",
  "UNIT.ADJUST": "Stock adjusted",
  "BRAND.CREATE": "Brand added",
  "BRAND.UPDATE": "Brand updated",
  "BRAND.DEACTIVATE": "Brand deactivated",
  "BRAND.DELETE": "Brand deleted",
  "CATEGORY.CREATE": "Category added",
  "CATEGORY.UPDATE": "Category updated",
  "CATEGORY.DEACTIVATE": "Category deactivated",
  "CATEGORY.DELETE": "Category deleted",
  "COLOR.CREATE": "Color added",
  "COLOR.UPDATE": "Color updated",
  "COLOR.DEACTIVATE": "Color deactivated",
  "COLOR.DELETE": "Color deleted",
  "BANK_ACCOUNT.CREATE": "Bank account added",
  "BANK_ACCOUNT.UPDATE": "Bank account updated",
  "BANK_ACCOUNT.DELETE": "Bank account deleted",
  "BANK_ACCOUNT.SET_DEFAULT": "Default bank set",
  "USER.CREATE": "User added",
  "USER.UPDATE": "User updated",
  "COMPANY.UPDATE": "Company updated",
};
