export const ONBOARDING = {
  title: "Let's set up your store",
  subtitle: "Create your shop profile and administrator account. You'll sign in right after.",
  stepCompany: "Store details",
  stepSettings: "Preferences",
  stepBanks: "Bank accounts",
  stepAdmin: "Administrator",
  companyTitle: "Tell us about your store",
  companySubtitle: "This is shown on receipts and printed documents. You can change it anytime in Settings.",
  settingsTitle: "Region & currency",
  settingsSubtitle: "Defaults for invoices, receipts and reports.",
  banksTitle: "Add bank accounts",
  banksSubtitle: "Optional — these appear as payment choices and on receipts. You can add more later in Settings.",
  adminTitle: "Create the administrator account",
  adminSubtitle: "This is the account you'll use to sign in. You can add more staff later in Settings.",
  doneTitle: "You're all set",
  doneSubtitle: "Your store and administrator account are ready.",
  storeName: "Store name",
  storeNamePlaceholder: "e.g. Fig Mobile",
  tagline: "Tagline",
  taglinePlaceholder: "One-line description (optional)",
  address: "Address",
  addressPlaceholder: "Shop address (optional)",
  phone: "Phone",
  phonePlaceholder: "0300-1234567",
  email: "Email",
  emailPlaceholder: "shop@example.com",
  yourName: "Your full name",
  yourNamePlaceholder: "e.g. Arslan Wahab",
  username: "Username",
  usernamePlaceholder: "e.g. ARSLAN",
  usernameHint: "Used to sign in",
  pin: "Choose a PIN",
  pinHint: "Exactly 4 digits — used to sign in",
  next: "Next",
  back: "Back",
  finish: "Finish setup",
  signingIn: "Signing in…",
  storeNameRequired: "Enter your store name",
  nameRequired: "Enter your full name",
  usernameRequired: "Enter a username",
  pinInvalid: "PIN must be exactly 4 digits",
  created: "Store ready",
  goToLogin: "Go to sign in",
  addBank: "Add bank account",
  bankName: "Bank name",
  bankNamePlaceholder: "e.g. Meezan",
  accountName: "Account name",
  accountNamePlaceholder: "e.g. Business",
  accountTitle: "Account title",
  accountTitlePlaceholder: "Account title (optional)",
  accountNumber: "Account number",
  accountNumberPlaceholder: "Account number",
  iban: "IBAN",
  ibanPlaceholder: "IBAN (optional)",
  currency: "Currency",
  timezone: "Timezone",
  skip: "Skip",
} as const;